name: Go

on:
  push:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: go build -o ./kaigon main.go
  
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Launch Server
      run: sudo supervisorctl reload
